---
:backends:
  - json
  - yaml

:hierarchy:
  - local
  - '%{operatingsystem}'
  - '%{::environment}'
  - common

:yaml:
  :datadir: /vagrant/hieradata

:json:
  :datadir: /vagrant/hieradata

:logger: console